[2023-11-26T15:05:29.792+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: your_etl_dag.download_currency manual__2023-11-26T15:05:27.194267+00:00 [queued]>
[2023-11-26T15:05:29.799+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: your_etl_dag.download_currency manual__2023-11-26T15:05:27.194267+00:00 [queued]>
[2023-11-26T15:05:29.799+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2023-11-26T15:05:29.809+0000] {taskinstance.py:1380} INFO - Executing <Task(DownloadCurrencyOperator): download_currency> on 2023-11-26 15:05:27.194267+00:00
[2023-11-26T15:05:29.817+0000] {standard_task_runner.py:57} INFO - Started process 1054 to run task
[2023-11-26T15:05:29.825+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'your_etl_dag', 'download_currency', 'manual__2023-11-26T15:05:27.194267+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpiahid85r']
[2023-11-26T15:05:29.833+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask download_currency
[2023-11-26T15:05:29.946+0000] {task_command.py:415} INFO - Running <TaskInstance: your_etl_dag.download_currency manual__2023-11-26T15:05:27.194267+00:00 [running]> on host bbdd398234f2
[2023-11-26T15:05:30.026+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='your_etl_dag' AIRFLOW_CTX_TASK_ID='download_currency' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T15:05:27.194267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-26T15:05:27.194267+00:00'
[2023-11-26T15:05:30.363+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/custom_operators.py", line 76, in execute
    download_currency_to_csv()
  File "/opt/airflow/dags/custom_operators.py", line 13, in download_currency_to_csv
    currency_data.to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 737, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 599, in check_parent_directory
    if not parent.is_dir():
  File "/usr/local/lib/python3.8/pathlib.py", line 1422, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/local/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/airflow/dags'
[2023-11-26T15:05:30.381+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=your_etl_dag, task_id=download_currency, execution_date=20231126T150527, start_date=20231126T150529, end_date=20231126T150530
[2023-11-26T15:05:30.394+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task download_currency ([Errno 13] Permission denied: '/root/airflow/dags'; 1054)
[2023-11-26T15:05:30.443+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T15:05:30.470+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
